
version: '3.2'

services:
    redis:
        image: redis:alpine

    will:
        build:
          context: .
          dockerfile: Dockerfile
        image: heywill/will:latest
        ports:
            - 8080:8080
        depends_on:
            - redis